model:
  checkpoint: outputs/best.ckpt
  type: wavlm
  wavlm:
    pretrained_name: microsoft/wavlm-base-plus
    freeze_encoder: false
  cnn_melspec:
    n_mels: 128
    n_fft: 1024
    hop_length: 320

data:
  sample_rate: 16000
  audio_dir: ../dataset/test
  audio_column: audio_name
  num_workers: 4
  batch_size: 8
  crop:
    enable: true
    min_sec: 3.0
    max_sec: 5.0
    mode: center

output:
  path: predictions.csv
