model:
  checkpoint: outputs/best.ckpt
  type: wavlm
  wavlm:
    pretrained_name: microsoft/wavlm-base-plus
    freeze_encoder: false
  cnn_melspec:
    n_mels: 128
    n_fft: 1024
    hop_length: 320

data:
  sample_rate: 16000
  audio_dir: ../dataset/test
  audio_column: audio_name
  num_workers: 8
  batch_size: 16
  crop:
    enable: true
    min_sec: 3.0
    max_sec: 5.0
    mode: center  # Options: 'center', 'random', 'start', 'end'
    
# Decision threshold for classification (default: 0.5)
# - Lower (e.g., 0.4-0.45): classify more samples as Real (class 1)
# - Higher (e.g., 0.55-0.6): classify more samples as AI (class 0)
decision_threshold: 0.45

output:
  path: predictions.csv
